[tool.poetry]
name = "courses-oop"
version = "0.1.0"
description = ""
authors = ["andranik <andranik2009@rambler.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
